### ISSUE TITLE
应用商店版插件开启会导致视频详情页无法加载其他资源

### ISSUE THREAD

**Issue by ch634421335** [lxfater/BilibiliSummary#7]
打开插件后点开视频，有一定概率无法加载评论区和右侧推荐列表视频封面，而且点击收藏等操作会提示让重新登录，但是多刷新几次就好了，怀疑是异步阻塞导致某些资源未加载成功。
[img1](https://img1.imgtp.com/2023/03/08/1iOjy26V.jpg)
[img2](https://img1.imgtp.com/2023/03/08/d0Fa3tkO.jpg)

**Comment by lxfater** [comment]
@lxfater 不用怀疑，就是，后面我看能不能修复。我已经尽力了。你有啥想法吗？

**Comment by lxfater** [comment]
不用怀疑，就是，后面我看能不能修复。我已经尽力了。你有啥想法吗？ @ch634421335

**Comment by ch634421335** [comment]
> 不用怀疑，就是，后面我看能不能修复。我已经尽力了。你有啥想法吗？ @ch634421335

我查看了一下控制台，每次无法加载的时候必定报这个错
```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```
我尝试克隆项目本地启动调试，但是无法下载'ai-bridge'这个依赖包，我在谷歌上搜索这个问题，找到了一些回复。
> https://github.com/nuxt/nuxt/issues/5800  

>https://stackoverflow.com/questions/62124873/nuxt-js-failed-to-execute-appendchild-on-node-this-node-type-does-not-supp  

但排名靠前的都是说在nuxtjs中会出现这个问题，给的解决方案是用 `v-if` 或者 `v-show`来加载元素。  
我不确定是否能解决，但是看他们的问题描述似乎和现在的情况很相似。因为我无法启动项目，所以抱歉无法帮上更多的忙了。  

---
附上报错记录  
```
btools.js:310 Btools Success: 已开启
btools.js:310 Btools Success: 获取图片
btools.js:310 Btools Success: 链接转换
stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                                          Release undefined@no release yet         \/            \/                                       Powered by @bilibili/jinkela-core@2.8.11
stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7 
        
       Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:41277)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:57626)
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:57257)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:57712)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:61050)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60985)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:61450)
    at t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:34442)
    at a.r (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68575)
    at vn.get (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26777)
    at new vn (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26695)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68599
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68746)
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:94394)
    at init (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:19529)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60761)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:61450)
    at t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:34442)
    at a.r (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68575)
    at vn.get (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26777)
    at new vn (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26695)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68599
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68746)
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:94394)
    at init (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:19529)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60761)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:61450)
    at t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:34442)
    at a.r (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68575)
    at vn.get (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26777)
    at new vn (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26695)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68599
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68746)
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:94394)
    at init (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:19529)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60761)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60985)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60985)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60985)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60985)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:61450)
    at t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:34442)
    at a.r (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68575)
    at vn.get (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26777)
    at new vn (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:26695)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68599
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:68746)
    at Sn.$mount (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:94394)
    at init (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:19529)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7:60761)
vn.get @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7
vn @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7
(匿名) @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7
Sn.$mount @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7
Sn.$mount @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:7
(匿名) @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:198
xf.onReady @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:198
Nf.onReady @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:198
(匿名) @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:198
n @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:1
(匿名) @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:181
n @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:1
(匿名) @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:1
(匿名) @ stardust-video.baf2860f67950774a97bd840e66dc0002241ec89.js:1
main.ts-e661b156.js:18 content-scripts {type: 'getSummary', content: '{"body":[{"from":3.46,"to":6.45,"sid":1,"location"…:77,"location":2,"content":"eq eq错了","music":0}]}'}

```
